## Getting Started & Introduction to Numpy ##
This introduction will teach you to do:

a) Learn to use the Jupyter Notebook and execute commands.

b) Creating Lists in Python.

c) Creating Numpy Arrays

d) Understand the difference between the Python list and Numpy arrays.

In [1]:
# Test whether you are able to print something
print 'Hi there! Machine Learning is easy!!'

#Notice that you can use \n
print ' Print To \n Next Line'

Hi there! Machine Learning is easy!!
 Print To 
 Next Line


In [5]:
# This is a list in Python. list is similar to an array!
list1 = [1,2,"Three"]

print list1

print list1[0]

print 'Elements in the list are:'
for element in list1:
    print element

[1, 2, 'Three']
1
Elements in the list are:
1
2
Three


In [6]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
#Import statement for importing Numpy.
import numpy as np

#This is how we can create a Numpy array
numpy_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
    
#print the array
print numpy_array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
#Array shape
numpy_array.shape

(3, 3)

In [14]:
#Indexing Numpy arrays
numpy_array[1,0]

4

In [18]:
#Slicing Numy arrays
numpy_array[1:3,1:3]


array([[5, 6],
       [8, 9]])

In [19]:
# Create 2 new Numpy arrays and add them together. Print the result.

na1 = np.array([1,2,3,4])
na2 = np.array([1,2,3,4])

# This is how we can add two Numpy arrays
na3 = na1 + na2

# print the array
print 'Addition of numpy arrays:'
print na3

Addition of numpy arrays:
[2 4 6 8]


## Check point ##

Using NumPy, we can much more efficiently analyze data than we can using lists.

NumPy arrays are more faster and efficient compared to Python lists.

**Exercise for later**

Try out other operations on Numpy Array - Subtraction, Multiplication, Dot Product! 

In [12]:
print np

<module 'numpy' from '/home/himanshu/anaconda2/lib/python2.7/site-packages/numpy/__init__.pyc'>
